### ISSUE TITLE
Integrate with regular logseq math equations

### ISSUE THREAD

**Issue by Pacman99** [hkgnp/darwis-mathlive-plugin#1]
When I'm viewing a document with the mathlive block its really jarring and out of place compared to the rest of my logseq page.

Would it be possible to only show the mathlive editor when the equation is clicked on, but otherwise render it as any other logseq equation? 

And a separate but related issue is that these equations don't get exported at all in the html page output. I'm not sure if thats something a plugin control, but it would be great if these equations just showed up in the html export like any other equation. Because I can currently export a page with latex equations as html and just add a header with the katex auto-render library to get the page and math expressions to export correctly. The mathlive blocks however just don't show up.

Also, thank you for creating the plugin! It is a really nice bonus from writing latex math expressions by hand.

**Comment by benjypng** [comment]
@Pacman99 Hi, unfortunately, Logseq doesn't actually support Mathlive out of the box. Hence, it's not in the marketplace. This means that the current implementation is actually a workaround, and therefore the editor will be persistent. 

As for the HTML export, it is for the same reason. Unfortunately, Mathlive is not existing within Logseq, hence it does not appear.

I am not sure if there are workarounds though, but it is really quite unlikely given that it's a workaround.

Sorry about that!

**Comment by benjypng** [comment]
@Pacman99 I've done a simple update. May help with your rendering request.

As for exporting to HTML, I've done further digging and there is no simple way to control it on the HTML output with just a static HTML file.

**Comment by Pacman99** [comment]
Thank you for responding and the new feature! I really like the convert to latex feature.

I was trying to experiment a bit to see if I could add a hook to any math expression block being edited, but I can't find a way to do that. None of the logseq APIs work well for regular logseq blocks.
