### ISSUE TITLE
Dialogue box doesn't show up in Logseq v0.7.1

### ISSUE THREAD

**Issue by Explorare** [hkgnp/darwis-mathlive-plugin#3]
**[ENV]**
Windows 10 21H1
Logseq v0.7.1
darwis-mathlive-plugin v1.1.0

**[Issue]**
The dialogue box doesn't show up. Only the output will show up if I append it manually.

**[Screenshots]**
![image](https://user-images.githubusercontent.com/5090766/171809403-3330ff5b-72cd-4467-ba92-fada85c24b97.png)
![image](https://user-images.githubusercontent.com/5090766/171809467-d0403611-08c6-4afb-9d1d-aaf2b947e475.png)

**Comment by benjypng** [comment]
Was it working before?

**Comment by Explorare** [comment]
Don't know. I just enabled this plugin.
Does it work in your side?
Is this plugin fully self-contained or requiring some JS library from CDN?

**Comment by benjypng** [comment]
It fully works on my side. Did you try restarting Logseq?
It is sell contained.

**Comment by Explorare** [comment]
I have tried disable all other plugins and back to the default theme, but still, no dialogue showed up.

**Comment by nhan000** [comment]
@Explorare it works fine for me
Windows 10 21H2
Logseq 0.7.3
